config/routes.rb
Cookbook::Application.routes.draw do
  resources :recipes, :ingredients

  root to: 'recipes#index'
end

#  Prefix Verb   URI Pattern                     Controller#Action
#         recipes GET    /recipes(.:format)              recipes#index
#                 POST   /recipes(.:format)              recipes#create
#      new_recipe GET    /recipes/new(.:format)          recipes#new
#     edit_recipe GET    /recipes/:id/edit(.:format)     recipes#edit
#          recipe GET    /recipes/:id(.:format)          recipes#show
#                 PATCH  /recipes/:id(.:format)          recipes#update
#                 PUT    /recipes/:id(.:format)          recipes#update
#                 DELETE /recipes/:id(.:format)          recipes#destroy
#     ingredients GET    /ingredients(.:format)          ingredients#index
#                 POST   /ingredients(.:format)          ingredients#create
#  new_ingredient GET    /ingredients/new(.:format)      ingredients#new
# edit_ingredient GET    /ingredients/:id/edit(.:format) ingredients#edit
#      ingredient GET    /ingredients/:id(.:format)      ingredients#show
#                 PATCH  /ingredients/:id(.:format)      ingredients#update
#                 PUT    /ingredients/:id(.:format)      ingredients#update
#                 DELETE /ingredients/:id(.:format)      ingredients#destroy
#            root GET    /                               recipes#index

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :quantities
	has_many :recipes, through: :quantities
end

app/models/ingredient_measurement.rb
class IngredientMeasurement < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/ingredient_quantity.rb
class IngredientQuantity < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/ingredients.rb
class Ingredient < ActiveRecord::Base
	has_many :recipes
end

app/models/ingredients_measurement.rb
class IngredientsMeasurement < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
  accepts_nested_attributes_for :ingredients
end

#one to many relationship

app/models/ingredients_quantity.rb
class IngredientsQuantity < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/quantity.rb
class Quantity < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :quantities
	has_many :ingredients, through: :quantities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@recipes = Recipe.all
		@ingredients = Ingredient.all
	end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :load_ingredient, only: [:show, :edit, :update, :destroy]
  
  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
    @ingredient.quantities.build
  end

  def create
    @ingredient = Ingredient.new ingredient_params
    redirect_to(@ingredient)
  end

  def show
  end

  def edit
  end

  def update
    @ingredient.update ingredient_params 
    redirect_to @ingredient 
  end

  def destroy
    @ingredient.destroy
    redirect_to(ingredients_path)
  end

  def load_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  private
    def ingredient_params
      params.require(:ingredient).permit(:name, :brand, :image, :quantities)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :load_recipe, only: [:show, :edit, :update, :destroy]
 
  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create recipe_params
    redirect_to(recipe)
  end

  def show
  end

  def edit
  end

  def update
    @recipe.update_attributes recipe_params
    redirect_to(@recipe)
  end
  
  def destroy
    @recipe.delete
    redirect_to(@recipes_path)
  end

  def load_recipe
    @recipe = Recipe.find(params[:id])
  end

  private
    def recipe_params
      params.require(:recipe).permit(:name, :course, :cooktime, :servingsize, :instructions, :quantities)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/homes/index.html.erb
<ul class="nav nav-pills">
  <li>
	<%= link_to('All Recipes', recipes_path) %>
  </li>
    <li>
    <%= link_to('All Ingredients', ingredients_path) %>
  </li>
</ul>

<% @recipes.each do |recipe| %>
  <div class="row">
     <div class="col-md-4 col-sm-4">
      <p class="lead"><%= link_to(recipe.name, recipe) %>
      <p><%= recipe.course %>
      <p><%= recipe.cooktime %>
      <p><%= recipe.servingsize %>
      <p><%= recipe.instructions %>
      <p><% recipe.ingredients.each do |i|%>
      	<%= i[:name] %></br>
      <% end %>
      <!--  TODO: Add code to display ingredients! this is something I can't seem to get work! -->
    </div>
  </div>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>
  <br>
  <%= f.label :brand %>
  <%= f.text_field :brand %>
  <br>

  <p><p>
  <%= f.submit  class: "btn btn-primary" %>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>
<%= render :partial => 'form' %>

app/views/ingredients/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Ingredient', new_ingredient_path) %>
  </li>
</ul>


<% @ingredients.each do |ingredient| %>
  <div class="row">
     <div class="col-md-4 col-sm-4">
      <p class="lead"><%= link_to(ingredient.name, ingredient) %>
      <p><%= ingredient.name %>
      <p><%= ingredient.brand %>
    </div>
  </div>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>
<%= render :partial => 'form' %>

app/views/ingredients/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Ingredient', new_ingredient_path) %></li>
  <li><%= link_to('Edit Ingredient', edit_ingredient_path(@ingredient)) %></li>
  <li><%= link_to('Delete Ingredient', @ingredient, :method => :delete, :confirm => 'Are you sure?') %></li>
  <div class='spacer'></div>
</ul>

<div class="row">
  <div class="col-md-5 col-sm-5">
    <p class="lead"><%= @ingredient.name %></p>
    <p><%= @ingredient.name %>
    <p><%= @ingredient.brand %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @ingredient do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, :autofocus => true %>
  <br>
  <%= f.label :brand %>
  <%= f.text_field :brand %>
  <br>
  <p><p>
  <%= f.submit  class: "btn btn-primary" %>
<% end %>

app/views/recipes/index.html.erb
<ul class="nav nav-pills">
  <li>
    <%= link_to('New Recipe', new_recipe_path) %>
  </li>
</ul>


<% @recipes.each do |recipe| %>
  <div class="row">
     <div class="col-md-4 col-sm-4">
      <p class="lead"><%= link_to(recipe.name, recipe) %>
      <p><%= recipe.course %>
      <p><%= recipe.cooktime %>
      <p><%= recipe.servingsize %>
      <p><%= recipe.instructions %>
<!--        TODO: Add code to display ingredients!å  -->
      <% recipe.ingredients.each do |ingredient|%>
      <div class="row">
          <p><%= ingredient.name %>
          <p><%= ingredient.brand %>
        <% end %>
      </div>

      
    </div>
  </div>
<% end %>

app/views/recipes/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Recipe', new_recipe_path) %></li>
  <li><%= link_to('Edit Recipe', edit_recipe_path(@recipe)) %></li>
  <li><%= link_to('Delete Recipe', @recipe, :method => :delete, :confirm => 'Are you sure?') %></li>
  <div class='spacer'></div>
</ul>

<div class="row">
  <div class="col-md-5 col-sm-5">
    <p class="lead"><%= @recipe.name %></p>
    <p><%= @recipe.course %>
    <p><%= @recipe.cooktime %>
    <p><%= @recipe.servingsize %>
    <p><%= @recipe.instructions %>
  </div>

  <!-- TODO: Display the ingredients in the show page -->
  <div class="col-md-7 col-sm-7">
    <% @recipe.ingredients.each do |ingredient| %>
      <%= @ingredient.name %>
      <%= image_tag(@ingredient.image,  size: "40x40") %>
    <% end %>
  </div>
 </div>